# Generated by Django 5.2.17 on 2026-09-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_multi_tenant_rbac'),
        ('projects', '0003_add_pmo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company'),
        ),
    ]
