# Generated by Django 5.2.17 on 2026-09-22 07:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billing_entity',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='category_a',
            field=models.CharField(blank=True, max_length=150, verbose_name='Project Category-A'),
        ),
        migrations.AddField(
            model_name='project',
            name='category_b',
            field=models.CharField(blank=True, max_length=150, verbose_name='Project Category-B'),
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Time'),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Ongoing'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_leads',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='lob_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lob_head_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='man_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Project Man Days'),
        ),
        migrations.AddField(
            model_name='project',
            name='overrun_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='percent_complete',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='pmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmo_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='PO No.'),
        ),
        migrations.AddField(
            model_name='project',
            name='po_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='po_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_group',
            field=models.CharField(blank=True, max_length=150, verbose_name='Project Group / LOB'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('MRA', 'MRA'), ('NON_MRA', 'Non MRA')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='unique_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='working_emp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Working Emp'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sales Region'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Ongoing'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20),
        ),
    ]
