# Generated by Django 5.2.17 on 2026-09-22 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_multi_tenant_rbac'),
        ('projects', '0007_project_pmo_dashboard_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Project ID'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_project_code_per_company'),
        ),
    ]
