# Generated by Django 5.2.17 on 2026-09-22 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_multi_tenant_rbac'),
        ('projects', '0006_project_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_contact', models.CharField(blank=True, max_length=150)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('QUALIFICATION', 'Qualification'), ('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('HOLD', 'Hold'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('probability', models.PositiveSmallIntegerField(default=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('lead_source', models.CharField(blank=True, max_length=150)),
                ('solution', models.TextField(blank=True)),
                ('technology', models.CharField(blank=True, max_length=150)),
                ('competitor', models.CharField(blank=True, max_length=150)),
                ('decision_maker', models.CharField(blank=True, max_length=150)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_projects', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_projects', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects_created', to=settings.AUTH_USER_MODEL)),
                ('linked_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_project', to='projects.project')),
                ('pmo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmo_deals', to=settings.AUTH_USER_MODEL)),
                ('presales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presales_deals', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_deals', to=settings.AUTH_USER_MODEL)),
                ('sales_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_deals', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
