# Generated by Django 5.2.17 on 2026-09-22 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_multi_tenant_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, choices=[('IN', 'India'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('SG', 'Singapore'), ('AE', 'United Arab Emirates'), ('JP', 'Japan'), ('CN', 'China'), ('BR', 'Brazil'), ('ZA', 'South Africa'), ('NZ', 'New Zealand'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('IE', 'Ireland'), ('MX', 'Mexico'), ('RU', 'Russia'), ('KR', 'South Korea'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('NG', 'Nigeria'), ('EG', 'Egypt'), ('SA', 'Saudi Arabia'), ('IL', 'Israel'), ('TR', 'Turkey'), ('PL', 'Poland'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('BE', 'Belgium')], max_length=2)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
