# Generated by Django 5.2.17 on 2026-09-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_short_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('IN', 'India'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('SG', 'Singapore'), ('AE', 'United Arab Emirates'), ('JP', 'Japan'), ('CN', 'China'), ('BR', 'Brazil'), ('ZA', 'South Africa'), ('NZ', 'New Zealand'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('IE', 'Ireland'), ('MX', 'Mexico'), ('RU', 'Russia'), ('KR', 'South Korea'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('NG', 'Nigeria'), ('EG', 'Egypt'), ('SA', 'Saudi Arabia'), ('IL', 'Israel'), ('TR', 'Turkey'), ('PL', 'Poland'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('BE', 'Belgium')], max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNSPECIFIED', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=50),
        ),
    ]
