# Generated by Django 5.2.17 on 2026-09-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_multi_tenant_rbac'),
        ('users', '0004_profile_extras_and_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Company Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('TEAM_LEAD', 'Team Lead'), ('MEMBER', 'Member'), ('CLIENT', 'Client'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=30),
        ),
    ]
