# Generated by Django 5.2.17 on 2026-09-21 09:34
#
# Renames the existing two-tier roles into the new three-tier hierarchy:
#   old SUPER_ADMIN (platform-wide)   -> GLOBAL_ADMIN
#   old ADMIN       (company admin)   -> SUPER_ADMIN
# Order matters: SUPER_ADMIN must be renamed to GLOBAL_ADMIN *before* ADMIN is
# renamed to SUPER_ADMIN, otherwise the newly-renamed rows would be re-matched
# and renamed a second time.

from django.db import migrations, models


def rename_roles_forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="SUPER_ADMIN").update(role="GLOBAL_ADMIN")
    User.objects.filter(role="ADMIN").update(role="SUPER_ADMIN")


def rename_roles_backward(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="SUPER_ADMIN").update(role="ADMIN")
    User.objects.filter(role="GLOBAL_ADMIN").update(role="SUPER_ADMIN")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_multi_tenant_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GLOBAL_ADMIN', 'Global Admin'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('TEAM_LEAD', 'Team Lead'), ('MEMBER', 'Member'), ('CLIENT', 'Client'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=30),
        ),
        migrations.RunPython(rename_roles_forward, rename_roles_backward),
    ]
