# Generated by Django 5.2.17 on 2026-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_three_tier_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_capacity_hours',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
    ]
