# Generated by Django 5.2.17 on 2026-09-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='territory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GLOBAL_ADMIN', 'Global Admin'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES_MANAGER', 'Sales Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SALESPERSON', 'Salesperson'), ('TEAM_LEAD', 'Team Lead'), ('MEMBER', 'Member'), ('CLIENT', 'Client'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=30),
        ),
    ]
