# Generated by Django 5.2.17 on 2026-09-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sales_roles_and_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidebar_order',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
