# Generated by Django 5.2.17 on 2026-09-20 19:03

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=files.models.attachment_upload_path),
        ),
    ]
